### Login with Demo User
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{demoEmail}}",
  "password": "{{demoPassword}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
    client.log("Access Token: " + response.body.accessToken);
%}

### Refresh Token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.log("New Access Token: " + response.body.accessToken);
%}
