/*
 * BoringOldCRM - Open-source multi-tenant CRM
 * Copyright (C) 2026 Ricardo Salvador
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Source: https://github.com/N0t4R0b0t/BoringOldCRM
 */
package com.bocrm.backend.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import tools.jackson.databind.JsonNode;

import java.time.LocalDateTime;

/**
 * Represents a customer record within a tenant schema.
 *
 * <p>Customers are the primary entity in BOCRM. Each customer belongs to exactly one tenant
 * (identified by {@code tenantId}) and is stored in that tenant's schema. This entity demonstrates
 * the standard pattern for all tenant-scoped CRM entities: scalar fields + JSONB custom data + timestamps.
 *
 * <p><strong>Two JSONB Columns</strong>:
 * <ul>
 *   <li><strong>customData</strong>: The complete raw custom field values (full fidelity). Used in
 *     detail views where all data is relevant. Example: {@code {"sales_stage": {"currentIndex": 2}, "annual_revenue": 5000000}}</li>
 *   <li><strong>tableDataJsonb</strong>: Denormalized display fields extracted from custom_data for
 *     list view rendering. Contains only frequently-displayed fields for performance. Example: {@code {"sales_stage_label": "Proposal", "annual_revenue": "$5M"}}</li>
 * </ul>
 *
 * <p>WHY two columns? List pages render hundreds of rows; fetching and rendering all custom data for each
 * row is wasteful. Instead, services explicitly extract display-relevant fields into tableDataJsonb at write time.
 * On read, list endpoints use tableDataJsonb (small, pre-formatted); detail endpoints use customData (complete).
 *
 * <p><strong>Tenant Isolation</strong>: The {@code tenantId} field is required (NOT NULL) and must always
 * match the current TenantContext. Services must verify this before returning a customer:
 * {@code if (!customer.getTenantId().equals(tenantId)) throw new ForbiddenException("Access denied");}
 *
 * <p><strong>Timestamps</strong>: {@code createdAt} and {@code updatedAt} are managed by {@code @PrePersist}
 * and {@code @PreUpdate} lifecycle hooks. They are never manually set.
 *
 * @see com.bocrm.backend.service.CustomerService#toDTO(Customer, Long) how customData vs tableDataJsonb are used in DTOs
 * @author Ricardo Salvador
 * @since 1.0.0
 */
@Entity
@Table(name = "customers")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Customer {
    /**
     * Unique identifier for this customer record. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The tenant ID that owns this customer. Required; must match TenantContext for access control.
     * Every service method must verify: {@code if (!customer.getTenantId().equals(tenantId)) throw ForbiddenException}
     */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /**
     * Customer name. Required; unique within each tenant (enforced at service level).
     */
    @Column(nullable = false)
    private String name;

    /**
     * Customer status. Standard values: "active", "inactive", "prospect", "customer", "lost".
     * Extensible via custom fields; this is just the primary status field.
     */
    @Column(nullable = false)
    private String status;

    /**
     * User ID of the customer owner. Used for access control and notification.
     * If set, notifications are sent to this user when the customer is assigned.
     */
    @Column(name = "owner_id")
    private Long ownerId;

    /**
     * Full custom field values as JSONB. Contains all admin-defined custom fields for this customer.
     * Format: {@code {"field_key": value, "workflow_key": {"currentIndex": 1}, ...}}
     *
     * <p>WHY JsonNode? It's flexible — custom fields can be any JSON type (string, number, array, object).
     * Stored in Postgres as JSONB for indexing and querying; deserialized to JsonNode for Java manipulation.
     *
     * <p>Never replace this wholesale. When updating, use {@code ObjectNode.setAll(newValues)} to merge
     * new fields with existing ones (see CustomerService.updateCustomer).
     *
     * @see com.bocrm.backend.service.CustomerService#updateCustomer(Long, UpdateCustomerRequest) the merge pattern
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "custom_data", columnDefinition = "jsonb")
    private JsonNode customData;

    /**
     * Denormalized custom fields extracted for list-view rendering. Contains only display-relevant fields.
     * Example: {@code {"sales_stage": "Proposal", "industry": "Technology"}}
     *
     * <p>WHY denormalized? Rendering 100 rows with 20 custom fields each (full serialization) is expensive.
     * Services extract high-value fields at write time; list endpoints use this column instead.
     *
     * <p>Always synchronized with customData by the service layer (see CustomerService.createCustomer).
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "table_data_jsonb", columnDefinition = "jsonb")
    private JsonNode tableDataJsonb;

    /**
     * When this record was created. Set automatically by {@link #onCreate()} and never updated.
     * Immutable after creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * When this record was last updated. Updated automatically by {@link #onUpdate()} on every mutation.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Customer's industry (e.g., "Technology", "Healthcare"). Optional scalar field.
     * Can also be stored as a custom field for more flexibility.
     */
    private String industry;

    /**
     * Customer's website URL. Optional scalar field.
     */
    private String website;

    /**
     * Free-form notes about the customer. Optional scalar field.
     */
    private String notes;

    /**
     * JPA lifecycle hook called before INSERT. Initializes createdAt and updatedAt to now.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * JPA lifecycle hook called before UPDATE. Updates updatedAt to now.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
