#!/usr/bin/env bash
# =============================================================================
# BOCRM — first-time install script
# Tested on: Debian 12, Ubuntu 22.04/24.04 (Proxmox VM or LXC)
# Usage:  bash scripts/install.sh
# =============================================================================
set -euo pipefail

COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

require_root() {
  [[ $EUID -eq 0 ]] || error "Run this script as root (or with sudo)."
}

# ── Docker ────────────────────────────────────────────────────────────────────
install_docker() {
  if command -v docker &>/dev/null; then
    success "Docker already installed ($(docker --version | cut -d' ' -f3 | tr -d ','))"
    return
  fi
  info "Installing Docker…"
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg lsb-release
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/$(. /etc/os-release && echo "$ID")/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/$(. /etc/os-release && echo "$ID") \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
  success "Docker installed"
}

# ── Env file ──────────────────────────────────────────────────────────────────
gen_secret() { openssl rand -hex 32; }

prompt() {
  local var="$1" prompt="$2" default="$3"
  local value
  read -rp "$(echo -e "${YELLOW}${prompt}${NC} [${default}]: ")" value
  echo "${value:-$default}"
}

prompt_secret() {
  local var="$1" prompt="$2"
  local value
  read -rsp "$(echo -e "${YELLOW}${prompt}${NC} (leave blank to auto-generate): ")" value
  echo
  echo "${value:-$(gen_secret)}"
}

prompt_optional() {
  local var="$1" prompt="$2"
  local value
  read -rp "$(echo -e "${YELLOW}${prompt}${NC} (optional, press Enter to skip): ")" value
  echo "${value:-}"
}

build_env() {
  if [[ -f "$ENV_FILE" ]]; then
    warn ".env already exists — skipping env setup. Delete it to reconfigure."
    return
  fi

  echo
  echo -e "${CYAN}━━━ Configuration ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo "Secrets (passwords, JWT key) will be auto-generated if left blank."
  echo

  local db_pass rabbitmq_pass redis_pass jwt_secret
  local anthropic openai gemini tavily
  local http_port

  db_pass=$(prompt_secret DB_PASSWORD "Database password")
  rabbitmq_pass=$(prompt_secret RABBITMQ_PASSWORD "RabbitMQ password")
  redis_pass=$(prompt_secret REDIS_PASSWORD "Redis password")
  jwt_secret=$(prompt_secret JWT_SECRET "JWT signing secret (min 32 chars)")
  echo
  echo -e "${CYAN}At least one AI provider key is needed for the assistant:${NC}"
  anthropic=$(prompt_optional ANTHROPIC_API_KEY "Anthropic API key")
  openai=$(prompt_optional OPENAI_API_KEY "OpenAI API key")
  gemini=$(prompt_optional GEMINI_API_KEY "Gemini API key")
  tavily=$(prompt_optional TAVILY_API_KEY "Tavily search key (optional)")
  echo
  http_port=$(prompt HTTP_PORT "Host port to expose the app on" "80")

  cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh — keep this file private

JWT_SECRET=${jwt_secret}
DB_PASSWORD=${db_pass}
RABBITMQ_PASSWORD=${rabbitmq_pass}
REDIS_PASSWORD=${redis_pass}

ANTHROPIC_API_KEY=${anthropic}
OPENAI_API_KEY=${openai}
GEMINI_API_KEY=${gemini}
TAVILY_API_KEY=${tavily}

HTTP_PORT=${http_port}
EOF
  chmod 600 "$ENV_FILE"
  success ".env written"
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  echo -e "${CYAN}"
  echo "  ╔══════════════════════════════╗"
  echo "  ║   Boring Old CRM — install   ║"
  echo "  ╚══════════════════════════════╝"
  echo -e "${NC}"

  require_root

  # Must run from the repo root
  [[ -f "$COMPOSE_FILE" ]] || error "Run this script from the repository root."

  install_docker
  build_env

  info "Building and starting services (this takes a few minutes on first run)…"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --build

  # Wait for the frontend to be reachable
  local port
  port=$(grep '^HTTP_PORT=' "$ENV_FILE" | cut -d= -f2)
  port="${port:-80}"

  info "Waiting for app to become ready…"
  local attempts=0
  until curl -sf "http://localhost:${port}" >/dev/null 2>&1; do
    sleep 3
    (( attempts++ ))
    [[ $attempts -lt 30 ]] || { warn "App didn't respond after 90 s — check: docker compose -f $COMPOSE_FILE logs"; break; }
  done

  local ip
  ip=$(hostname -I | awk '{print $1}')

  echo
  echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${GREEN}  BOCRM is running!${NC}"
  echo -e "  URL:  ${CYAN}http://${ip}:${port}${NC}"
  echo -e "  Logs: docker compose -f ${COMPOSE_FILE} logs -f"
  echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

main "$@"
